package:
  name: julia
  version: "0.5.0"

source:
  fn: julia-0.5.0-linux-x86_64.tar.gz
  url: https://julialang.s3.amazonaws.com/bin/linux/x64/0.5/julia-0.5.0-linux-x86_64.tar.gz
  sha256: 5b18bbfcc39b2214ce5ec5d3c186aa39dbcab0bc465415353d44762fe14d1183

build:
  skip: True # [osx]
  rpaths:
    - lib/julia/
  number: 0

requirements:
  build:
    - gcc # [linux]
    - llvm # [osx]
    - zlib
  run:
    - zlib
    - libgcc # [linux]

about:
  home: http://julialang.org/
  license: MIT
  license_file: LICENSE.md
  summary: A high-performance dynamic programming language for data science

test:
  commands:
    - "julia -v"
