package:
  name: julia
  version: "0.5.0"

source:
  fn: julia-0.5.0.tar.gz
  url: https://github.com/JuliaLang/julia/releases/download/v0.5.0/julia-0.5.0-full.tar.gz
  sha256: 732478536b6dccecbf56e541eef0aed04de0e6d63ae631b136e033dda2e418a9

build:
  rpaths:
    - lib/julia/
  number: 0

requirements:
  build:
    - gcc # [linux]
    - llvm # [osx]
    - zlib
  run:
    - zlib
    - libgcc # [linux]

about:
  home: http://julialang.org/
  license: MIT
  license_file: LICENSE.md
  summary: A high-performance dynamic programming language for data science

test:
  commands:
    - "julia -v"
